spring:
    application:
        #应用名称
        name: eureka-client-producer
    zipkin:
        base-url: http://localhost:9411/
        sender:
            type: web
    sleuth:
        sampler:
            probability: 1.0
server:
    port: 8762
#指定注册中心服务地址，可以有多个地址
eureka:
    client:
        serviceUrl:
            defaultZone: http://peer1:8761/eureka/,http://peer2:8080/eureka/