spring:
    application:
        name: eureka_client_fegin_consumer
    #docker启动zipkin链路追踪，访问http://localhost:9411/zipkin/来查看链路调用关系
    zipkin:
        base-url: http://localhost:9411/
        sender:
            type: web
    sleuth:
        sampler:
            probability: 1.0
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 8765
#打开fegin的服务熔断机制，默认关闭
feign:
    hystrix:
        enabled: true