spring:
    application:
        name: eureka_server
server:
    port: 8080

eureka:
    instance:
        hostname: peer2
    client:
        #表明此应用是eureka服务注册中心而不是客户端
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
#            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
            defaultZone: http://peer1:8761/eureka/